### ISSUE TITLE
Wii VC rom runs at 17 FPS on European Wii

### ISSUE THREAD

**Issue by Farlander-001** [Zelllll/tml#11]
As title says, this game runs at 17 FPS on European Wii console. Same happens on Dolphin Emulator with EU firmware.

**Comment by Farlander-001** [comment]
As a temporary workaround, if you have installed USBLoader GX, turn Force NTSC480p mode in game options

**Comment by Zelllll** [comment]
Yeah the game is intended for NTSC so you might things like this when playing on PAL.
