### ISSUE TITLE
Hitting a Big Skulltula with your sword and sword beam at the same time won't kill it.

### ISSUE THREAD

**Issue by MasterMathew** [Zelllll/tml#13]
When you hit the big skulltula with the sword and the sword beam at the same time, while it's facing you, the skulltula will start it's death animation, but then the swinging animation from the hit takes over, and it doesn't die. 

It's not a major glitch or anything, but it's a bit strange.

EDIT: Here's a video example: https://youtu.be/52rDkLIfxb4

**Comment by DoomRater** [comment]
I noticed this one too but didn't think much of it, and just kept my distance.

**Comment by Zelllll** [comment]
Yeah its a little weird lol. It is just how the collision checking works in the game though.
