### ISSUE TITLE
Issues from playthough on 1.2

### ISSUE THREAD

**Issue by ethanccss** [Zelllll/tml#14]
Beat the game and it was amazing. Though I noticed some things.

Zombie Glitch: I was thinking of ways (ended up being the wrong way) to kill the zombies behind the bars to move the woman from the chest and was using my charged sword beam to attack the zombies from the inside. While attacking the right side zombie it scared(froze) me in the charged sword beam position (I was basically up against the bars) when I unfroze I was on the other side of the bars. Something about that interaction caused me to glitch forward through the bars. Which meant I had to leave out the zombie side door and run around and enter from the front again. Not a huge glitch but was weird.

Peahat Camera: After killing the peahat the camera remained focused in the air where the peahat died instead of panning down to where the chest was spawning. Just a small quality improvement suggestion. 

Deku Pass: I was surprised and thought the game glitched when I went back to show the deku guards the pass but they were gone. Felt weird to not have to show them the pass in order to gain access to the new area. Maybe this was a glitch but it didnt feel right, the lady beside them also acted as if they were still there (but did change her response after entering and coming back to speak to her). Talking to the guards after obtaining the pass then having them disappear into the ground would make this feel much more complete. 

Thanks for the awesome mod!

**Comment by Zelllll** [comment]
None of these are really glitches necessarily, but I'm glad you enjoyed the mod.
