### ISSUE TITLE
Game crashes when beating the first mini boss after a game over

### ISSUE THREAD

**Issue by Oradimi** [Zelllll/tml#15]
I'm playing the game on Project64, and after getting a game over against the first mini boss, and trying again immediately, the game crashed once I beat it. I tried again after restarting the game and not dying once, and the game went without a crash. It might be worth noting it might not be because of the game over, but because of the fullscreen (I didn't use fullscreen when I beat it), but it's unlikely.

**Comment by Zelllll** [comment]
This was already fixed in 1.3.
