### ISSUE TITLE
Skull Kid bombchu game sometimes does not give you Piece of Heart

### ISSUE THREAD

**Issue by IronYoshi64** [Zelllll/tml#17]
Hey there!

For me at least, I notice if you play through the hack for a while, and get to the Skull kid mini-game where you have to blow up the bomb-eyes, I swear it sometimes just does not give you the heart piece correctly, even when hitting both eyes over 2-3 times.

The only way I found to possibly sometimes fix this is to Save game, completely close out of your emu, and reload it and try again.

**Comment by tech6hutch** [comment]
You have to hit both eyes within a short time. It took me a bit to figure that out.

**Comment by IronYoshi64** [comment]
> You have to hit both eyes within a short time. It took me a bit to figure that out.
> 
> Edit: perhaps that minigame could be made a bit clearer, either by editing Skull Kid's description of it, or him clarifying if you hit each eye too long apart.

Oh ok. That makes sense actually. Thanks. Also yeah that will be nice to do xD

**Comment by Zelllll** [comment]
Yes, hit them both at once and it will work correctly.
