### ISSUE TITLE
Bombchu Shop

### ISSUE THREAD

**Issue by nhcarrigan** [Zelllll/tml#18]
The Bombchu shop will not check if your inventory is full before selling you more Bombchus. 

Steps to reproduce:
1. Ensure you have 160 rupees.
2. Purchase 20 Bombchu (this should fill your inventory)
3. Purchase another 20 Bombchu
--Rupees are deducted, but you still only have 20 Bombchu.

Running on Project 64, Version 2.3.2.202
Running TML version 1.4

**Comment by Pimacs07** [comment]
I had the same.

PLUS! Sellers give limited bombchu... What happen when you fail all your attempt and can't buy bombchu anymore? There's no jar who gives them at this point.

**Comment by SalsaAndFriends** [comment]
@Pimacs07 After you free Monktown there will be many jars that have Bombchus in them.

**Comment by Zelllll** [comment]
There are pots in the grotto in the Deep Woods if you for some reason bought all the Bombchu and used them. They also of course are scattered all throughout the world after Monktown.
