### ISSUE TITLE
Last dungeon item create a bug

### ISSUE THREAD

**Issue by Pimacs07** [Zelllll/tml#19]
Hi.

In one of the last room of the dungeon, you need to take down a red wall, pass an elevator who is rumbling before going up, go back to the crystal, bring down the blue wall and activate the hourglass to pass this wall.

BUT ! If you activate the hourglass while you were on the elevator, you're stuck under the plateform and cannot grab the edge to leave the hole.

I think it's the very last room who gives you the very last key to go to the last boss :)

**Comment by Zelllll** [comment]
Typically the elevator is supposed to crush Link and void out. If not I suppose save and reset.
