### ISSUE TITLE
Meeko and Mykel dialogue inconsistency

### ISSUE THREAD

**Issue by AndrewDiess** [Zelllll/tml#2]
When talking to the Deku brothers the left brother's dialogue needs to change when it names itself. Currently he names himself as Mykel even though the right brother refers to him as Meeko.

**Comment by Zelllll** [comment]
Fixed this in the latest build, will release in a few minutes. thanks for finding it

**Comment by AndrewDiess** [comment]
No problem! Amazing job you've all done.
