### ISSUE TITLE
Wii: broken audio in PAL60

### ISSUE THREAD

**Issue by Wuerfel21** [Zelllll/tml#20]
Running the game in any PAL mode (actual system region is irrelevant) will produce stuttering audio. PAL50 not working is understandable, but PAL60 should definitely work. (Forcing NTSC fixes the audio, but will for many PAL people lead to no color or red screen)

I assume this is a bug in the N64 VC emulator that might be a bit tough to fix:  I think some choice is being based on wehter the selected video mode is PAL/NTSC (which is utterly irrelevant to anything as PAL60 has the same timing as NTSC) rather than it's actual frame rate.

I think I might have an idea of how this could be worked around (patching all video modes in the VC executable to PAL60 and then forcing NTSC), will have to mess around with it a bit tomorrow.

**Comment by Wuerfel21** [comment]
OK, replacing NTSC mode with PAL60  just leads to black screen when that mode is activated.
Patching in a PAL60 compatible VC emulator fails because there is no PAL60 VC game with expansion pack support.

**Comment by Wuerfel21** [comment]
I did however figure out how to fix it for Dolphin users:
**Set your WADs region to USA, not region-free!**

**Comment by Zelllll** [comment]
There might be some way to edit the wad to be region free or something, but without even having a Wii to test, let alone a PAL Wii there isn't too much I can do unfortunately. Forcing NTSC somehow seems to be the best way to go though, if possible.

**Comment by Wuerfel21** [comment]
You can use AnyRegionChanger to change a Wii to PAL (there is no HW difference between Wii regions).

But as I said, setting the region code to USA will cause Dolphin to force NTSC and thus correct audio (important, since changing the emulated region is a bit non-obvious)
