### ISSUE TITLE
 Kokiri forest music is heard for a second during the storm

### ISSUE THREAD

**Issue by angelhp** [Zelllll/tml#21]
there is a small bug with sound in the Kokiri Forest once the sword is obtained, and the storm begins
It can be heard when entering and leaving the houses.
the error in question is that the original kokiri forest music is heard for a second before the storm is heard

**Comment by DoomRater** [comment]
I heard it too in my 1.3 playthrough but didn't think to report it.  I wasn't sure if it's just the music event firing before the storm effects can be called or if it can actually be addressed.

**Comment by Zelllll** [comment]
this is just how the game works
