### ISSUE TITLE
My save made me skip ahead!

### ISSUE THREAD

**Issue by meaninglessname** [Zelllll/tml#4]
I arrived in Monktown and made my way up to the castle area. I found only an empty room with several elements that obviously needed fire to continue (an unlit torch, a spider web blocking a path down). I saved my game and reset the N64....when I came back, I was in a different room with three Gerudos!

I mean, I'm grateful for this glitch, as I was truly stuck there (no lit torches to be found in the immediate area). But it's still a glitch, and I have no idea if I just missed an item that will make progression impossible. Guess I'll find out.

**Comment by SalsaAndFriends** [comment]
You are technically in the same area but I do wonder why it chose to start you off in the room below instead of the room you saved in.

**Comment by Zelllll** [comment]
This is not a bug.
