### ISSUE TITLE
The Business Scrubs were selling the wrong items, couldn't access Baba Garden

### ISSUE THREAD

**Issue by mdtauk** [Zelllll/tml#5]
The Business Scrubs were selling the wrong items, couldn't access Baba Garden

**Comment by Zelllll** [comment]
This will be fixed in the next release.

**Comment by mdtauk** [comment]
> This will be fixed in the next release.

Thank you @Zelllll  Will I need to replay, or will my save file be good?

**Comment by Zelllll** [comment]
Your save will work fine.

**Comment by theroflcoptr** [comment]
Hmm, I ended up needing to start fresh but this was fixed in 1.3. Thanks!
