### ISSUE TITLE
Fire Keese description still mentions Deku Shield

### ISSUE THREAD

**Issue by DoomRater** [Zelllll/tml#6]
Link is carrying the Hero's shield, which doesn't burn up, right?

**Comment by Zelllll** [comment]
Oh that's kind of funny. If there are enough actual bugs found though to warrant releasing another version I'll fix it, so I'll keep this issue open for now.

**Comment by DoomRater** [comment]
No worries, I totally understand this is minor and not gameplay affecting at all.

**Comment by Zelllll** [comment]
Fixed, will be changed in the new 1.4 release.
