### ISSUE TITLE
Translation ?

### ISSUE THREAD

**Issue by SteF4444** [Zelllll/tml#7]
Hi, very good work !
Is it possible to tanslate it ?
My language is french and it would be nice to play the game in french. Unfortunaltely, your patch only accept the US version of Zelda.
If I can help to translate I will be happy to proceed !

Best regards

**Comment by Zelllll** [comment]
If you want to translate it, go for it.

**Comment by SteF4444** [comment]
Heu... Ok but how to unpack the package ?
