### ISSUE TITLE
Kokiri Forest text issues in v1.3

### ISSUE THREAD

**Issue by dacicus-occidens** [Zelllll/tml#8]
Several lines have unnecessary commas:
* will only open to those, who know her song!
* I was so busy cutting this tree, that
* We Kokiris are lost, without them
* chasing that demon, and being the hero
* I also lost my fairy, doesn't mean

Several lines should have commas around the player's name:
* Where did Navi go NAME -> go, NAME
* Welcome back to the forest NAME -> forest, NAME
* You're back NAME -> back, NAME
* Please save them NAME -> them, NAME
* I hate to admit it NAME but -> it, NAME, but

Some lines need a comma inserted:
* Did it take Navi too -> Navi, too
* If you can cut down this tree then -> tree, then

This comma should be replaced with either a semicolon or a period:
* I can't leave the Forest, we Kokiris can't

One Kokiri first says that Saria's house is on "the hill to my right."  If you speak with her again, she says that it's on the hill to the left.  The location is unclear in the second variation, especially since the player could be facing in several directions.

The Kokiri who's trying to cut down the tree has variable coloring of "withered tree."  Sometimes "tree" is red, but sometimes it isn't.

**Comment by Zelllll** [comment]
Thanks a lot for the great feedback! I have since fixed all of these issues, and this will be changed in version 1.4. Thanks again!
